version: "3.7"

services:
  spring-boot-admin:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-spring-boot-admin-server:latest
    networks:
      - dev_overlay
    ports:
      - "8082:8080"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
      restart_policy:
        condition: any
    environment:
      charon.env: dev
      spring.cloud.inetutils.preferred-networks: 10.0.3
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: charon-spring-boot-admin-server
networks:
  dev_overlay:
    external: true
